name: Verify

on:
  pull_request:
    branches:
      - main

jobs:
  static-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
      - run: pnpm install
      - run: pnpm format
      - run: pnpm lint
